### ISSUE TITLE
on IONIC

### ISSUE THREAD

**Issue by ainulya16** [devarthurribeiro/cordova-plugin-bluetooth-printer#1]
is available to print on bluetooth printer using "bluetoothSerial.write" ?

**Comment by devarthurribeiro** [comment]
so, what is your printer model?

**Comment by ainulya16** [comment]
EPPOS EP5802AI. i've not tried before. should you explain me sample code? is it just connect->print->disconnect?

**Comment by devarthurribeiro** [comment]
yes it is possible with this model. I can teach you how. you are Brazilian?

**Comment by devarthurribeiro** [comment]
try this, 
after the connection:

```
var text = '';
text += "\x1B\x61\x01\";
text += 'Your text';
text += " \x0A\x0A\x0A";
bluetoothSerial.write(text ,function () {
  alert("ok");
}, function () {
  alert("erro");
});
```

**Comment by ainulya16** [comment]
i 've try not using this code and i got delayed time to print some text. so how to give next line, align "right", etc? is just "\n" ??
and i'll try this code. thanks a lot. by the way i'm indonesian 😁

**Comment by devarthurribeiro** [comment]
ok, put the result here. if you have the manual can use other flags,
just put in the string!
